### ISSUE TITLE
local docker server in 0.20.0 leads to page_not_found

### ISSUE THREAD

**Issue by johannes-becker-otto** [h2oai/wave#1229]
Hello everyone

#### h2o Wave Version, OS

0.20.0, Docker runs in Unix

#### Actual behavior
Running server and app in Docker worked before
Now it's
```
server-1  | 2022/02/02 13:01:46 # ┌────────────────┐ H2O Wave 
server-1  | 2022/02/02 13:01:46 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.20.0 20220131055911
server-1  | 2022/02/02 13:01:46 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
server-1  | 2022/02/02 13:01:46 # └────────────────┘
server-1  | 2022/02/02 13:01:46 #
server-1  | 2022/02/02 13:01:46 # {"address":":445","base-url":"/","t":"listen","web-dir":"/wave/www"}
server-1  | 2022/02/02 13:01:47 # {"t":"page_not_found","url":"/"}
app-1     | INFO:     Application startup complete.
server-1  | 2022/02/02 13:01:56 # {"addr":"172.18.0.1:58712","route":"/","t":"ui_add"}
```
The app then remains frozen at the h2o wave symbol

#### Expected behavior
```
server-1  | 2022/02/02 13:16:23 # ┌────────────────┐ H2O Wave 
server-1  | 2022/02/02 13:16:23 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.19.0 20211029183310
server-1  | 2022/02/02 13:16:23 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
server-1  | 2022/02/02 13:16:23 # └────────────────┘
server-1  | 2022/02/02 13:16:23 #
server-1  | 2022/02/02 13:16:23 # {"address":":445","t":"listen","webroot":"/wave/www"}
app-1     | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
app-1     | INFO:     Started reloader process [8] using statreload
app-1     | INFO:     Started server process [10]
app-1     | INFO:     Waiting for application startup.
server-1  | 2022/02/02 13:16:24 # {"host":"http://app:8000/","route":"/","t":"app_add"}
app-1     | INFO:     Application startup complete.
```
Interestingly, if I install 0.19.0 for the app and 0.20.0 for the server it still works

#### Steps To Reproduce
I hope I add everything of importance
server:
      - H2O_WAVE_PORT=:445
      - H2O_WAVE_ADDRESS=http://localhost:445/

CMD ./waved -access-key-id "$H2O_WAVE_ACCESS_KEY_ID" \
  -access-key-secret "$H2O_WAVE_ACCESS_KEY_SECRET" \
  -tls-cert-file "$DOMAIN_CERT_PATH" \
  -tls-key-file "$DOMAIN_KEY_PATH" \
  -listen "$H2O_WAVE_PORT"
      
app:
      - H2O_WAVE_APP_ADDRESS=http://app:8000/
      - H2O_WAVE_ADDRESS=http://server:445/
      - H2O_WAVE_DOMAIN=http://localhost:10101

CMD uvicorn --host="0.0.0.0" --reload main:main

All the best
Hannes

**Comment by lo5** [comment]
Hi @johannes-becker-otto - Thank you for reporting the issue. 

Do you mind posting the Dockerfile (maybe a stripped down minimal version) so that I can repro this? It's not clear to me how `H2O_WAVE_DOMAIN` is used, since it's not an env var used by the Wave server or apps.

Thanks in advance!

**Comment by johannes-becker-otto** [comment]
[h2o_docker_minimal.zip](https://github.com/h2oai/wave/files/7992874/h2o_docker_minimal.zip)
Hi @lo5 ,
gladly, I hope the zipped minimal example works.
I tested it on my machine `docker compose up --build` (Docker Engine v20.10.11)
If you change the h2o-wave version in the app Dockerfile (in ".\") to 0.19.0 it works and you see the app in
http://localhost:10101/ 
All the best
Hannes

**Comment by johannes-becker-otto** [comment]
Hi @lo5 
If you have any feedback, otherwise I'll start my futile approach of trial and error again.
All the best
Hannes

**Comment by lo5** [comment]
Thanks for providing the repro.

The following env vars shouldn't have the trailing `/`.

```
environment:
  - H2O_WAVE_APP_ADDRESS=http://app:8000                                                                       │~
  - H2O_WAVE_ADDRESS=http://server:445   
```

See docs:
- https://wave.h2o.ai/docs/configuration#h2o_wave_app_address
- https://wave.h2o.ai/docs/configuration#h2o_wave_address

Once you make that change, your setup should work for both 0.19.0 and 0.20.0.

I would recommend moving the Wave version to an `ARG` since it's only required during the build stage, like this:

```
version: "3.9"
services:
  server:
    build:
      context: ./server
      args:
        WAVE_VERSION: 0.20.0
    ports:
      - "10101:445"
    dns:
      - 8.8.8.8 #GOOGLE DNS
    environment:
      - H2O_WAVE_PORT=:445
  app:
    build:
      context: .
      args:
        WAVE_VERSION: 0.20.0
    dns:
      - 8.8.8.8 #GOOGLE DNS
    environment:
      - H2O_WAVE_APP_ADDRESS=http://app:8000
      - H2O_WAVE_ADDRESS=http://server:445
    volumes:
      - .:/app:ro
    stdin_open: true
    tty: true
```

The corresponding Dockerfile for the Wave server (could use `FROM alpine` for quicker builds):

```
FROM python:3.8
ARG WAVE_VERSION
RUN bash -c 'wget --directory-prefix=/tmp/ \
  https://github.com/h2oai/wave/releases/download/v${WAVE_VERSION}/wave-${WAVE_VERSION}-linux-amd64.tar.gz \
  && tar -xzf /tmp/wave-${WAVE_VERSION}-linux-amd64.tar.gz \
  && mv wave-${WAVE_VERSION}-linux-amd64 /wave'
WORKDIR /wave
EXPOSE "${H2O_WAVE_PORT}"
CMD ./waved -listen "$H2O_WAVE_PORT"
```

Also, in your other Dockerfile, avoid `uvicorn --reload` in production.

Hope this helps!
